export const ACTION_TYPE = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PRODUCT: "SET_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  ADD_PRODUCT: "ADD_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  SET_MODAL_IS_EDITING: "SET_MODAL_IS_EDITING",
};
